/** Default UI copy and catalog display names (Simplified Chinese). */

export const zh = {
  sidebarAgentTeams: "Agent Team",
  sidebarAgentCrew: "Agent 班组",
  openAgentTeams: "打开 Agent Team",
  openAgentCrew: "打开 Agent 班组",
  launchTeamCommand: "启动 Agent Team",
  roles: "Role",
  teams: "Team",
  newRole: "新建 Role",
  newTeam: "新建 Team",
  editRole: "编辑 Role",
  editTeam: "编辑 Team",
  searchRoles: "搜索 Role",
  searchTeams: "搜索 Team",
  chooseTeam: "选择 Team",
  chooseRole: "选择 Role",
  noMatchingRoles: "没有匹配的 Role",
  importRuflo: "导入 Ruflo Role",
  importOk: "已导入 Ruflo Role，请确认每个 Role 的 Profile。",
  importFail: "无法导入示例 Team。",
  emptyTitle: "还没有 Role 或 Team",
  emptyBody:
    "导入 Ruflo Role 目录（编码、研究、蜂群、GitHub、SPARC 等），再为每个 Role 绑定 Paseo Profile。",
  loading: (name: string) => `正在加载${name}…`,
  loadFail: (name: string) => `无法加载${name}`,
  parseFail: "存储的数据无法解析",
  retry: "重试",
  reset: "重置",
  resetTitle: "重置已存储的数据？",
  resetBody: "将用默认内容替换这份无法读取的文档。其他目录不受影响。",
  catalogRoles: "Role",
  catalogTeams: "Team",
  catalogPreferences: "偏好",
  launchContextFail: "无法加载启动上下文",
  name: "名称",
  description: "描述",
  mission: "使命",
  icon: "图标",
  id: "ID",
  idLocked: "创建后无法更改 ID。",
  idSlugHint: "使用小写 slug：字母开头，后接字母、数字或连字符。",
  responsibilities: "职责",
  restrictions: "限制",
  systemPrompt: "系统提示",
  outputContract: "产出约定",
  preferredProfiles: "首选 Profile",
  fallbackProfiles: "备选 Profile",
  mcpServers: "高级：MCP servers（JSON）",
  mcpInvalid: "MCP servers 必须是最多 8 个 stdio、http 或 sse 配置。",
  enabled: "启用",
  cancel: "取消",
  save: "保存",
  saveFail: "保存失败",
  saving: "保存中…",
  add: "添加",
  addMember: "添加成员",
  moveMemberUp: "上移成员",
  moveMemberDown: "下移成员",
  removeMember: "移除成员",
  addProfile: "添加 Profile",
  hideProfiles: "收起 Profile",
  loadingProfiles: "正在加载 Profile…",
  refreshProfiles: "刷新 Profile",
  coordinator: "协调者",
  members: "成员",
  member: "成员",
  operatingRules: "运作规则",
  instanceLabel: "实例标签",
  instancePlaceholder: "后端 / 前端",
  role: "Role",
  unused: "未被使用",
  usedBy: (count: number) => `被 ${count} 个 Team 使用`,
  roleInUse: "Role 正在使用中",
  cannotDeleteRole: (name: string, teams: string) =>
    `无法删除 ${name}。它被以下 Team 使用：${teams}。`,
  ok: "确定",
  overwrite: "覆盖",
  conflictTitle: "内容已被更新",
  conflictRole: "另一台客户端已保存此目录。重新加载最新副本，或用当前 Role 覆盖。",
  conflictTeam: "另一台客户端已保存此目录。重新加载最新副本，或用当前 Team 覆盖。",
  idUsed: (kind: string, id: string) => `${kind} id「${id}」已被使用。`,
  roleKind: "Role",
  teamKind: "Team",
  missingRoles: (ids: string) => `缺失 Role：${ids}。`,
  membersCount: (count: number) => `${count} 名成员`,
  noProfile: "没有 Profile",
  missingProfile: (name: string) => `缺失 Profile：${name}`,
  defaultColor: "默认颜色",
  defaultIcon: "默认图标",
  dismissPicker: "关闭图标选择器",
  placeholderRoleName: "技术负责人",
  placeholderRoleDesc: "协调 Team 并汇总结果",
  placeholderMission: "这个 Role 为什么存在",
  placeholderTeamName: "编码团队",
  launchTitle: "启动 Agent Team",
  launch: "启动",
  launching: "启动中…",
  launched: "Team 已启动",
  launchFailed: "启动失败",
  task: "任务",
  workspace: "工作区",
  project: "项目",
  searchProjects: "搜索项目",
  chooseProject: "选择项目",
  noMatchingProjects: "没有匹配的项目",
  newWorkspace: "新建 Workspace",
  newWorkspaceTitle: "新 Workspace 名称",
  newWorkspaceHint: "在所选项目下新建 Workspace，然后启动 Team。不会使用已有会话。",
  creatingWorkspace: "正在创建 Workspace…",
  createWorkspaceFail: "无法创建 Workspace",
  copyKickoff: "复制启动消息",
  creatingCoordinator: "正在创建协调者…",
  creatingMember: (index: number, total: number) => `正在创建成员 ${index} / ${total}…`,
  sendingKickoff: "正在发送启动消息…",
  preferred: "首选",
  fallback: "备选",
  needsInput: "需要输入",
  failed: "失败",
  working: "工作中",
  ready: "就绪",
  idle: "空闲",
  closed: "已关闭",
  context: "上下文",
  currentWorkspace: "当前工作区",
  launchTeam: "启动 Team",
  refreshCrew: "刷新班组",
  filterAgents: "筛选智能体",
  filterPlaceholder: "按任务、模型、工作区筛选",
  loadAgentsFail: "无法加载智能体",
  loadingCrew: "正在加载班组",
  noAgents: "还没有智能体",
  noMatches: "没有匹配项",
  loadingCrewBody: "正在读取此工作区的智能体。",
  noAgentsBody: "启动一个智能体，或让它委派任务。班组会出现在这里。",
  noMatchesBody: "更改状态筛选或搜索文本。",
  agentWord: "个智能体",
  crewWord: "个班组",
  descendant: "个下级",
  elsewhere: "其他位置",
  elsewherePrefix: "其他位置：",
  expand: "展开",
  collapse: "收起",
  nudge: "轻推",
  interruptRedirect: "中断并改向",
  detach: "分离",
  archive: "归档",
  allow: "允许",
  deny: "拒绝",
  permissionRequest: "权限请求",
  permissionKind: "类型",
  permissionPayload: "载荷",
  permissionReview: "请审阅下面的待处理权限请求。明确允许或拒绝。",
  workingEllipsis: "处理中…",
  messageToSubagent: "发给子智能体的消息",
  nextStepPlaceholder: "这个智能体接下来该做什么？",
  nudgeSent: "已发送轻推",
  agentRedirected: "智能体已改向",
  subagentDetached: "子智能体已分离",
  subagentArchived: "子智能体已归档",
  agentActionFailed: "智能体操作失败",
  permissionAllowed: "已允许权限",
  permissionDenied: "已拒绝权限",
  permissionDecisionFailed: "权限决策失败",
  permissionAlreadyResolved: "权限请求已经处理过。",
  permissionUnreachable: "无法连接守护进程以响应权限请求。",
  deniedFromCrew: "已从 Agent 班组拒绝",
  request: "请求",
  now: "刚刚",
  copySuffix: "副本",
  missing: "缺失",
  teamFallback: "Team",
  agentsSuffix: "个智能体",
  teamDoesNotExist: "Team 不存在。",

  coordinatorMissing: (id: string) => `协调者 Role「${id}」不存在。`,
  memberMissing: (id: string) => `成员 Role「${id}」不存在。`,
  skippingDisabled: (label: string) => `跳过已禁用 Role ${label}。`,
  noEnabledMembers: "没有可启动的已启用成员。",
  exceedMax: (count: number, max: number) => `已启用成员（${count}）超过上限 ${max}。`,
  coordinatorProfileFail: (reason: string) => `无法解析协调者 Profile（${reason}）。`,
  memberProfileFail: (label: string, reason: string) =>
    `无法解析 ${label} 的 Profile（${reason}）。`,
  profileMissing: (label: string) => `Profile ${label} 缺失。`,
  providerUnavailable: (provider: string, reason?: string) =>
    `Provider ${provider} 不可用${reason ? `：${reason}` : ""}。`,
  usingFallback: (name: string) => `首选 Profile 缺失或不可用，改用备选 ${name}。`,
  createCoordinatorFail: "创建协调者智能体失败。",
  createMemberFail: (index: number, total: number) => `创建成员 ${index} / ${total} 失败。`,
  kickoffFail: "智能体已创建，但发送启动消息失败。请复制启动消息并在协调者对话中发送。",
  archivedCreated: "已归档创建的智能体。",
  keptCreated: "已保留创建的智能体。",
  taskRequired: "必须填写任务描述。",
  teamTitlePrefix: "[Team]",
  loadProfilesFail: "无法读取 Paseo Profile",
  coordinatorCannotMember: "协调者不能同时作为成员",
  duplicateNeedsLabel: "重复的 Role 需要实例标签",
} as const;

export const ROLE_ZH_NAMES: Record<string, string> = {
  "adaptive-coordinator": "自适应协调者",
  "agentic-payments": "智能支付",
  analyst: "分析师",
  "api-docs": "API 文档",
  architecture: "架构师",
  "backend-dev": "后端开发",
  "base-template-generator": "基础模板生成器",
  "benchmark-suite": "基准测试套件",
  "byzantine-coordinator": "拜占庭协调者",
  "cicd-engineer": "CI/CD 工程师",
  "code-analyzer": "代码分析器",
  "code-goal-planner": "代码目标规划师",
  "code-review-swarm": "代码审查蜂群",
  coder: "程序员",
  "collective-intelligence-coordinator": "集体智能协调者",
  "consensus-coordinator": "共识协调者",
  "crdt-synchronizer": "CRDT 同步器",
  "database-specialist": "数据库专家",
  "flow-nexus-app-store": "Flow Nexus 应用商店",
  "flow-nexus-auth": "Flow Nexus 认证",
  "flow-nexus-challenges": "Flow Nexus 挑战",
  "flow-nexus-neural": "Flow Nexus 神经",
  "flow-nexus-payments": "Flow Nexus 支付",
  "flow-nexus-sandbox": "Flow Nexus 沙箱",
  "flow-nexus-swarm": "Flow Nexus 蜂群",
  "flow-nexus-user-tools": "Flow Nexus 用户工具",
  "flow-nexus-workflow": "Flow Nexus 工作流",
  "github-modes": "GitHub 模式",
  "goal-planner": "目标规划师",
  "gossip-coordinator": "Gossip 协调者",
  "hierarchical-coordinator": "层级协调者",
  "issue-tracker": "议题跟踪器",
  "load-balancing-coordinator": "负载均衡协调者",
  "matrix-optimizer": "矩阵优化器",
  "memory-coordinator": "记忆协调者",
  "mesh-coordinator": "网状协调者",
  "migration-planner": "迁移规划师",
  "ml-developer": "机器学习开发",
  "mobile-dev": "移动开发",
  "multi-repo-swarm": "多仓库蜂群",
  "pagerank-analyzer": "PageRank 分析器",
  "perf-analyzer": "性能分析器",
  "performance-benchmarker": "性能基准测试",
  "performance-monitor": "性能监视器",
  "performance-optimizer": "性能优化器",
  planner: "规划师",
  "pr-manager": "PR 管理员",
  "production-validator": "生产验证器",
  "project-board-sync": "项目看板同步",
  "project-coordinator": "项目协调者",
  pseudocode: "伪代码",
  "python-specialist": "Python 专家",
  "queen-coordinator": "蜂后协调者",
  "quorum-manager": "法定人数管理器",
  "raft-manager": "Raft 管理器",
  refinement: "精炼",
  "release-manager": "发布管理员",
  "release-swarm": "发布蜂群",
  "repo-architect": "仓库架构师",
  researcher: "研究员",
  "resource-allocator": "资源分配器",
  reviewer: "审查员",
  "safla-neural": "SAFLA 神经",
  "scout-explorer": "侦察探索者",
  "security-auditor": "安全审计员",
  "security-manager": "安全管理器",
  "smart-agent": "智能体",
  "sona-learning-optimizer": "SONA 学习优化器",
  "sparc-coder": "SPARC 程序员",
  "sparc-coord": "SPARC 协调者",
  specification: "规格说明",
  "sublinear-goal-planner": "次线性目标规划师",
  "swarm-init": "蜂群初始化",
  "swarm-issue": "蜂群议题",
  "swarm-memory-manager": "蜂群记忆管理器",
  "swarm-pr": "蜂群 PR",
  "sync-coordinator": "同步协调者",
  "system-architect": "系统架构师",
  "task-orchestrator": "任务编排者",
  "tdd-london-swarm": "TDD London 蜂群",
  "test-architect": "测试架构师",
  "test-long-runner": "长时测试运行器",
  tester: "测试员",
  "topology-optimizer": "拓扑优化器",
  "trading-predictor": "交易预测器",
  "typescript-specialist": "TypeScript 专家",
  "v3-integration-architect": "V3 集成架构师",
  "v3-memory-specialist": "V3 记忆专家",
  "v3-performance-engineer": "V3 性能工程师",
  "v3-queen-coordinator": "V3 蜂后协调者",
  "v3-security-architect": "V3 安全架构师",
  "worker-specialist": "工人专家",
  "workflow-automation": "工作流自动化",
};

export const TEAM_ZH_NAMES: Record<string, string> = {
  "coding-team": "编码团队",
  "research-team": "研究团队",
  "analysis-team": "分析团队",
  "consensus-team": "共识团队",
  "core-team": "核心团队",
  "flow-nexus-team": "Flow Nexus 团队",
  "github-team": "GitHub 团队",
  "goal-team": "目标团队",
  "hive-mind-team": "蜂群思维团队",
  "optimization-team": "优化团队",
  "sparc-team": "SPARC 团队",
  "specialists-team": "专家团队",
  "sublinear-team": "次线性团队",
  "swarm-team": "蜂群团队",
  "templates-team": "模板团队",
  "testing-team": "测试团队",
  "v3-team": "V3 团队",
};

export const TEAM_ZH_DESCRIPTIONS: Record<string, string> = {
  "coding-team": "规划、实现、测试并独立审查一次软件变更。",
  "research-team": "用资料、核对和审慎结论来调查一个问题。",
  "analysis-team": "代码分析与质量评估。",
  "consensus-team": "拜占庭、Raft、Gossip 等共识与同步 Role。",
  "core-team": "规划、实现、研究、审查与测试的核心 Role。",
  "flow-nexus-team": "Flow Nexus 平台相关 Role。",
  "github-team": "PR、议题、发布与仓库协作。",
  "goal-team": "目标分解与规划。",
  "hive-mind-team": "蜂后、侦察、工人与集体智能。",
  "optimization-team": "负载、基准、监视与拓扑优化。",
  "sparc-team": "SPARC 规格、伪代码、架构与精炼。",
  "specialists-team": "语言、数据库、安全等单例专家。",
  "sublinear-team": "矩阵、PageRank、性能与交易预测。",
  "swarm-team": "自适应、层级与网状协调。",
  "templates-team": "记忆、迁移、SPARC 与任务编排模板。",
  "testing-team": "生产验证与 TDD 蜂群。",
  "v3-team": "V3 架构、记忆、性能与安全。",
};

export function zhRoleName(id: string, fallback: string): string {
  return ROLE_ZH_NAMES[id] ?? fallback;
}

export function zhTeamName(id: string, fallback: string): string {
  return TEAM_ZH_NAMES[id] ?? fallback;
}

export function zhTeamDescription(id: string, fallback: string): string {
  return TEAM_ZH_DESCRIPTIONS[id] ?? fallback;
}
